### ISSUE TITLE
golem node on raspberry pi 4 - old commit finally work

### ISSUE THREAD

**Issue by syahpian** [alexandre-abrioux/golem-node#61]
just want to inform you that after so long, finally old commit work on raspberry pi 4

(git checkout e5c29c5f83cd867cf316880d1e7f77de3060b5aa)

from https://github.com/alexandre-abrioux/golem-node/issues/44

current qemu version

![Image](https://github.com/user-attachments/assets/41e31615-5920-4f38-8e82-d4440f281530)

some golem node screenshot

![Image](https://github.com/user-attachments/assets/64f99772-fe33-4a13-965e-ff472fe4b78e)

![Image](https://github.com/user-attachments/assets/9dd09640-c66c-43ca-9573-a6a4f7d41003)

![Image](https://github.com/user-attachments/assets/f1f8bb4a-0cd9-43c6-bb06-798264f8ba71)

also, already try to compile latest commit, but it didnt work 

regards

**Comment by alexandre-abrioux** [comment]
Thanks for the feedback, @syahpian! As far as I know, Golem still does not support arm64, so I will close this for now.

> current qemu version
Why do you use QEMU, by the way? Your Raspberry Pi 4 CPU architecture is already arm64, I struggle to understand why you'd need QEMU on top of it.

By the way, you could use QEMU to emulate the x86-64 architecture on your Raspberry Pi, and try to run the x86-64 Docker image directly. You can add the following line to the `docker-compose.yaml` to force Docker to run the x86-64 image:
```yaml
  node:
    container_name: ${COMPOSE_PROJECT_NAME}_node
    image: aabrioux/golem-node:${DOCKER_IMAGE_TAG}
    restart: always
    platform: linux/amd64
```
It might be very slow, though, so not very useful for Golem workloads.
